### ISSUE TITLE
KeyError: 'total_results'

### ISSUE THREAD

**Issue by Shinoby1992** [Eldorados/script.module.metahandler#49]
Greetings from germany 

20:33:23 T:123145312575488  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.8.6
20:33:23 T:123145303990272  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
20:33:23 T:123145303990272  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.8.6
20:33:23 T:123145303453696  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
20:33:23 T:123145303453696  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.8.6
20:33:23 T:123145312575488  NOTICE: metahandler: No SQLite rows requiring update
20:33:24 T:123145312575488  NOTICE: Previous line repeats 35 times.
20:33:24 T:123145312575488  NOTICE: Traceback (most recent call last):
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/plugin.video.xstream/default.py", line 28, in <module>
                                                run()
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/plugin.video.xstream/xstream.py", line 14, in run
                                                parseUrl()
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/plugin.video.xstream/xstream.py", line 192, in parseUrl
                                                function()
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/plugin.video.xstream/sites/kinox_to.py", line 471, in showCinemaMovies
                                                _cinema(oGui)
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/plugin.video.xstream/sites/kinox_to.py", line 500, in _cinema
                                                oGui.addFolder(oGuiElement, oParams, bIsFolder = False, iTotal = total)
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/plugin.video.xstream/resources/lib/gui/gui.py", line 60, in addFolder
                                                oGuiElement.getMeta(oGuiElement._mediaType, imdbID, mode = self.metaMode)
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/plugin.video.xstream/resources/lib/gui/guiElement.py", line 221, in getMeta
                                                meta = oMetaget.get_meta(self._mediaType, self.__sTitle)
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/script.module.metahandler/lib/metahandler/metahandlers.py", line 943, in get_meta
                                                meta = self._get_tmdb_meta(imdb_id, tmdb_id, name, year)
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/script.module.metahandler/lib/metahandler/metahandlers.py", line 1355, in _get_tmdb_meta
                                                meta = tmdb.tmdb_lookup(name,imdb_id,tmdb_id, year)
                                              File "/Users/HumanKh/Library/Application Support/Kodi/addons/script.module.metahandler/lib/metahandler/TMDB.py", line 368, in tmdb_lookup
                                                if meta and meta['total_results'] == 0 and year:
                                            KeyError: 'total_results'

No Metadata getting loaded anymore in add-on
 "xStream"
which uses your metahandler 
im not sure if this problem occurred now with the latest update, because i didnt had it before...

Would be grateful and glad if you fix this :-))

**Comment by Eldorados** [comment]
Not trying to be rude, but you should ditch using the xstream addon, I won't support anything that has to do with them

**Comment by Shinoby1992** [comment]
is it personally or because of the content? hmmmm so lets say you hate them and don't want to support anything that has to do with them...does that mean this error is inserted from you that it won't work...or is there a really bug behind tmdb because they changed their website

please ignore that i said which add-on im using, i mean you tool getting used from many other addons too... :/ :-)?

**Comment by Eldorados** [comment]
I edited my reply, I confused xstream with istream (who I don't care for).. I would never put anything in to purposely break addons.. this update has been out for weeks now

Turn debugging on and post a full log file - not here but to xbmclogs.com and give me the link so I can see what's up

**Comment by Shinoby1992** [comment]
im glad i thought i have to cry and fix it somehow my self
of course i give you a full log: 
http://goo.gl/P2CkTb

I created the error 2 times, with start again the request and go to movies, that metahandler start searching i hope it helps 

now that we talk about this error, i would never come for  this issue but just to mention it now, another error i remember was that metahandler could not handle ä ü ö 
there is a german Movie like "Fuck you Göthe 2" it never found anything for it (fan art) 
just to mention :D 

thank you very much i appreciate that

**Comment by Eldorados** [comment]
So I should handle this error a bit better in metahandlers, but the root of the issue seems to be with the xstream addon, they need to properly decode the title to utf-8 before passing it in.. the title they gave metahandlers can't be parsed by TMDB and throws up a nasty error

I think you will need to try and notify the makers of the xstream addon, I believe they can be found at tvaddons.ag, but in the meantime I'll try to put in some code to protect from this error

**Comment by Shinoby1992** [comment]
Im gonna Tell him in his github repo 

Okay i understand....THe Problem is new like some days but he didnt pushed a update 
So its one new movie entry that does this error 
Hope your fix / protection is firstly enough 
Because it dont have to be that he is so fast solving THe problem 

Is there a way you can check for corrected decoding if not your script decodes it?

**Comment by Eldorados** [comment]
Character encoding is a HUGE pain for us.. I tried handling it before and was too much trouble trying to account for all the variations, so the addons have to do it first.. which they should be doing anyway to not cause any other issues when displaying the title in Kodi

**Comment by Shinoby1992** [comment]
i tried to fix it myself somehow, even if its just a short fix that it don't threw this nasty error and ignore that 1 title that it cannot handle,  but no way i have no clue xd
  ....i figured out the movie it cannot handle is Fuck you göthe 2

the link it try to access is
http://api.themoviedb.org/3/search/movie?language=de&api_key=af95ef8a4fe1e697f86b8c194f2e5e11&query=Fack%20ju%20G%C3hte%202

right unicode had to be 
%C3%B6 for ö

so yeah you are right invalid utf-8


i don't get it, the movie is out like 1 month, and also 1 month available and got used from metahandler
it never could load fan art, but it showed the right cover so im not sure if it was cover from metahandler and without fan art, or it was cover got without metahandler and from the file itself and thats the reason it never hat a fan art.
But...
neither you, than xstream updated and it worked 1 week ago and the whole last month in v. 2.9.0 in your metahandler, and xstream also didnt updated anything new, so why does it now threw this error the whole time and load nothing anymore :x

**Comment by Eldorados** [comment]
Yes, I saw everything in your log..

Is this the right movie? -
http://api.themoviedb.org/3/search/movie?language=de&api_key=af95ef8a4fe1e697f86b8c194f2e5e11&query=Fack%20ju%20G%C3%B6hte%202

The error is on the addon side, it's impossible for anything on metahandler
side to have created this in latest update as nothing was changed in that
area, and the location of the error is very obvious what the problem is

It likely never showed up because the movie was not listed on the addons
list of movies until now... ??

I've already given you all the information I can, this isn't my problem to
solve, you need to bug the xstream guys to do a fix and properly decode the
title to utf-8 before sending it into metahandlers

**Comment by Shinoby1992** [comment]
Yes thats the right movie

yeah i understand what you said, i already texted him on github hope he is gonna read and solve it
i think he will do it, i just try for short self fix somehow

No thats wrong, the movie showed up, but didnt had infos from metahandler so it got through metahandler, but metahandler just didnt gave fan art. Means it couldn't handle it but didnt threw error, and simply ignored it and showed other movies correctly. 

I did understand that its xstream fault, this bug did exist before i guess, but the threwing error and metahandler don't show the other movies is new. 

What exactly happened i don't know, didnt looked in log one week before

**Comment by Shinoby1992** [comment]
I just recovery a old backup from me from 15.10.15 now 
it has metahandler 2.8.0 and of course the old version of the oder add-on.
deleted all repos for not autoupdate 
and it get me the same error,  so i guess maybe tmdbs output is changed that it threw a other json error than before

i just try to somehow figure the bug out together and maybe you add a short "ignore if error" fix
 hope i don't make you angry :D

**Comment by Eldorados** [comment]
Why don't you edit the addon and add a line that decodes to the title to
utf-8 before sending into metahandlers?

**Comment by Shinoby1992** [comment]
im trying the whole time..
whats the function name thats getting fired for giving metahandler title name

**Comment by Eldorados** [comment]
Get_meta()                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Shinoby1992Sent: Friday, November 13, 2015 12:19 PMTo: Eldorados/script.module.metahandlerReply To: Eldorados/script.module.metahandlerCc: EldoradosSubject: Re: [script.module.metahandler] KeyError: 'total_results' (#49)im trying the whole time..
whats the function name thats getting fired for giving metahandler title name 

—Reply to this email directly or view it on GitHub.

**Comment by Shinoby1992** [comment]
sorry that we talking about a problem in another add-on, its just that you answer really fast and im glad you are try to help even if its not in your add-on and your fault, the add-on creator didnt answered so no idea if he read it already and will work on a fix, or if he is on vacation or whatever...

I solved it somehow after 100 different tries that i got from google...
encode it, decode it to utf-8 and whatever, still got everytime a error 
just one solution worked... i using this code: 

import re

def remove_unicode(string_data):
    """ (str|unicode) -> (str|unicode)

    recovers ascii content from string_data
    """
    if string_data is None:
        return string_data

    if isinstance(string_data, str):
        string_data = str(string_data.decode('ascii', 'ignore'))
    else:
        string_data = string_data.encode('ascii', 'ignore')

    remove_ctrl_chars_regex = re.compile(r'[^\x20-\x7e]')

    return remove_ctrl_chars_regex.sub('', string_data)

fieldValue = remove_unicode(STRING)


But my Output is 
"Fack ju GHTE 2"
not Fack ju Göhte 2

**Comment by Lynx187** [comment]
Hi,
just for clarification, the addon passes a utf-8 encoded string. If this string contains non-ascii chars isalnum() in __clean_name() in the TMDB.py usually filters them out even if they consist of two bytes. This won't cause an error. However, if the string contained non-ascii chars the resulting search string for TMBD is then wrong and the search will return no results.
If I pass a decoded string it would probably work but the printing to the log will cause crashes.
So, no __clean_name() for the seacrh string would be nice.

Now, why is Shinoby getting this strage error?
I guess on his system the encoding in the "locale" module is set to some iso-encoding or similar.
This would explain the different interpretation of the bytes (Ã¶ instead of ö) and the different behavior of isalnum() which lead in the end to the strage error (it filters only the second byte and leaves the first byte, which is thenn invalid utf-8).
